---
- name: Manage Firewall
  hosts: dev
  become: true
  tasks:
  - firewalld:
     zone: public
     state: enabled
     permanent: true
     icmp_block_inversion: true
     immediate: yes

  - firewalld:
     zone: drop
     state: enabled
     permanent: true
     icmp_block: echo-request
     immediate: yes

  - name: Redirect port 443 to 9443 with rich rule
    firewalld:
     rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=9443
     zone: public
     state: enabled
     permanent: true
     immediate: yes
     
