---
- name: HAProxy Server Configuration Playbook
  hosts: localhost
  become: true
  tasks:
  - name: Seting up the static hostname in the server machine
    hostname:
     name: haproxy-server
     use: systemd

  - name: Making entries in the /etc/hosts file for the server hostname & IP Address
    blockinfile:
     dest: /etc/hosts
     block: |
      172.31.34.42 haproxy-server
      172.31.47.158  node01
      172.31.35.38  node02
  
  - name: Installing haproxy,openssl and httpd packages in the machine
    yum:
     name:
      - haproxy
      - openssl 
      - mod_ssl
      - httpd
     state: latest
 
  - name: Creating /etc/pki/haproxy directory for the SSL private key file
    file:
     path: /etc/pki/haproxy 
     mode: '0755'
     state: directory

  - name: Generating the private key file
    openssl_privatekey:
     path: /etc/pki/haproxy/haproxy.key
     size: 2048

  - name: Generating Cerficate Sign Request(CSR)
    community.crypto.x509_certificate:
     path: '/etc/pki/haproxy/haproxy.crt'
     privatekey_path: '/etc/pki/haproxy/haproxy.key'
     force: true
     provider: selfsigned

  - name: Concatenating the key and certificate to a PEM file
    shell: cat /etc/pki/haproxy/haproxy.crt  /etc/pki/haproxy/haproxy.key > /etc/pki/haproxy/haproxy.pem

  - name: Copying the /etc/haproxy/haproxy.cfg file using ansible jinja template
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      force: true
 
  - name: Making changes in the /etc/rsyslog.conf file
    replace:
     dest: /etc/rsyslog.conf
     regexp: '^#module(load= "imudp")'
     replace: 'module(load= "imudp")'

  - name: Making changes in the /etc/rsyslog.conf file
    replace:
     dest: /etc/rsyslog.conf
     regexp: '^#input(type= "imudp" port="514")'
     replace: 'input(type= "imudp" port="514")'

  - name: Creating haproxy.conf file for the rsyslog
    copy:
     dest: /etc/rsyslog.d/haproxy.conf
     content: |
      local2.=info        /var/log/haproxy-access.log
      local2.notice       /var/log/haproxy-info.log
  
  - name: Restarting and enabling the rsyslog service
    service:
     name: rsyslog
     state: restarted
     enabled: yes

  - name: Turning on the haproxy_connect_any SELinux boolean
    command: setsebool -P haproxy_connect_any 1 

  - name: Starting and enabling haproxy service
    service:
     name: haproxy
     state: started
     enabled: yes      

- hosts: node1
  become: true
  tasks:
  - name: Seting up the static hostname in the node1 machine
    hostname:
     name: node01
     use: systemd
  
  - name: Making entries in the /etc/hosts file for the server hostname & IP Address
    blockinfile:
     dest: /etc/hosts
     block: |
      172.31.34.42 haproxy-server
      172.31.47.158  node01
      172.31.35.38  node02     
     insertafter: EOF
   
  - name: Installing HTTPD Packages in the machine
    yum:
     name: httpd
     state: latest
 
  - name: Creating the index.html file for node1
    copy:
     dest: "/var/www/html/index.html"
     content: <h1>HTTP Node1 - Welcome to First Apache Webserver</h1>

  - name: Starting and enabling httpd service
    service:
     name: httpd
     state: started
     enabled: yes 

- hosts: node2
  become: true
  tasks:
  - name: Seting up the static hostname in the node2 machine
    hostname:
     name: node02
     use: systemd
  
  - name: Making entries in the /etc/hosts file for the server hostname & IP Address
    blockinfile:
     dest: /etc/hosts
     block: |
      172.31.34.42 haproxy-server
      172.31.47.158  node01
      172.31.35.38  node02
     insertafter: EOF
   
  - name: Installing HTTPD Packages in the machine
    yum:
     name: httpd
     state: latest
 
  - name: Creating the index.html file for node1
    copy:
     dest: "/var/www/html/index.html"
     content: <h1>HTTP Node2 - Welcome to Second Apache Webserver</h1>

  - name: Starting and enabling httpd service
    service:
     name: httpd
     state: started
     enabled: yes 

