---
- name: MariaDB
  hosts: dev
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "P@$$word"
  tasks:
  - name: Create a new dataabse with name 'bobdata'
    mysql_db:
     name: bobdata
     state: present
     login_user: root
     login_password: "{{mysql_root_password }}"

