---
- name: Manage SELinux
  hosts: dev
  become: true
  tasks:
  - name: Allow apache to modify files in /tmp directory
    sefcontext:
     target: '/tmp(/.*)?'
     setype: httpd_sys_rw_content_t
     state: present
  - name: Apply SELinux file context
    command: restorecon -irv /tmp

